-- Run once in Supabase SQL Editor. The application does not auto-migrate.
create table if not exists public.morning_reports (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    report_date date not null,
    html_content text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint morning_reports_user_date_key unique (user_id, report_date)
);

create index if not exists morning_reports_user_latest_idx
    on public.morning_reports (user_id, report_date desc);

alter table public.morning_reports enable row level security;
drop policy if exists "Users can read own morning reports" on public.morning_reports;
create policy "Users can read own morning reports"
    on public.morning_reports for select to authenticated
    using ((select auth.uid()) = user_id);

-- Scheduled generation writes through the server's direct PostgreSQL role.
-- Browser users intentionally receive no INSERT/UPDATE/DELETE policy.
revoke all on table public.morning_reports from anon;
grant select on table public.morning_reports to authenticated;
