-- Task 13: encrypted per-user Kakao OAuth credentials.
-- Run once in Supabase SQL Editor before enabling Kakao OAuth.

create table if not exists public.kakao_credentials (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique references auth.users(id) on delete cascade,
    access_token_encrypted text not null,
    refresh_token_encrypted text not null,
    access_token_expires_at timestamptz null,
    refresh_token_expires_at timestamptz null,
    scopes text null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.kakao_credentials enable row level security;

-- OAuth tokens are server-only secrets. Authenticated browser clients must never
-- read or write this table directly. The backend uses its PostgreSQL connection.
revoke all on public.kakao_credentials from anon, authenticated;
