-- Task 11: one-time invite-only signup.
-- Run once in Supabase SQL Editor before deploying the matching application code.

create table if not exists public.invite_codes (
    id bigint generated by default as identity primary key,
    code_hash varchar(64) not null unique,
    label text,
    intended_email text,
    expires_at timestamptz,
    used_at timestamptz,
    used_by uuid unique references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    constraint invite_codes_hash_format check (code_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists invite_codes_intended_email_idx
    on public.invite_codes (lower(intended_email))
    where intended_email is not null;

alter table public.invite_codes enable row level security;

-- Invitations are server-admin data. Browser clients must never enumerate,
-- insert, update, or delete invite rows.
revoke all on table public.invite_codes from anon, authenticated;
revoke all on sequence public.invite_codes_id_seq from anon, authenticated;

-- Example creation workflow (do NOT store the plaintext code here):
-- 1. Generate a long random code locally.
-- 2. Compute SHA-256(code) and insert only the 64-char hex digest.
-- 3. Give the plaintext code to exactly one family member/friend.
--
-- insert into public.invite_codes (code_hash, label, intended_email, expires_at)
-- values ('<sha256-hex>', 'Family member 1', 'person@example.com', now() + interval '7 days');
